### PR TITLE
Generate Causal Rules

### PR DESCRIPTION
**Pull request by riccardocadei**
Add `generate_causal_rules()` function with effect modifiers filter for Rule Generation and respective tests.

### CODE REVIEW

**Review by Naeemkh — CHANGES_REQUESTED** [review]
Hi @riccardocadei, please return back the summary function. All S3 objects should have dedicated print, summary, and plot functions.

**Comment by riccardocadei** [comment]
Oh I am sorry, I didn't know it was mandatory. What is `summary()` purpose exactly? Before it was barely equal to the `print()` function. Should I just copy paste the `print()` function?

**Comment by Naeemkh** [comment]
No worries :). The print function mainly represents functional details, for example, fcall,  what kind of object it is, and so on. The summary function should focus more on the summary of the output data, for example, mean, median, number of missing values, and other details about the output data, not on the function itself.

**Comment by riccardocadei** [comment]
I re-added the print function in the other open PR since it is there where I removed first the print function.

**Review by Naeemkh — APPROVED** [review]

**Pull request merged**
